<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE airports [
<!ELEMENT airports (airport*)>
  <!ELEMENT airport (name, description, url, image?)>
  <!ATTLIST airport code CDATA #IMPLIED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
]>
<airports>
	<airport code="SYD">
		<name>Sydney</name>
		<description>Sydney airport is located in Sydney. It handles both domestic and international flights.</description>
		<url>https://www.sydneyairport.com.au/</url>
		<image>data/uploads/airport.png</image>
	</airport>
	<airport>
		<name>Brisbane</name>
		<description>Brisbane airport is located in Brisbane. It handles both domestic and international flights.</description>
		<url>https://www.bne.com.au/</url>
		<image></image>
	</airport>
	<airport>
		<name>Canberra</name>
		<description>Canberra airport is located in Canberra. It handles both domestic and international flights.</description>
		<url></url>
	</airport>
</airports>
