<?xml version="1.0" encoding="utf-8"?>
<!--Phillip Lord, c3401807 template.xml-->
<!DOCTYPE products [
<!--Defines parent elements-->
<!ELEMENT products (rental*)>
<!ELEMENT rental (title, url, image+, description, winePairing*, category, cost, tags*, parentalRating?, condition?, healthWarning?, powerUse, extras*, review*)>
<!ELEMENT review (userName, reviewText, rating)>
<!ELEMENT image (imgUrl, imgName)>
<!ELEMENT extras (cartridgeName, cartridgeSize)>

<!--Defines child elements of rental with PCDATA input-->
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT tags (#PCDATA)>
<!ELEMENT parentalRating (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT healthWarning (#PCDATA)>
<!ELEMENT winePairing (#PCDATA)>
<!ELEMENT powerUse (#PCDATA)>

<!--Defines child elements of image with PCDATA input-->
<!ELEMENT imgUrl (#PCDATA)>
<!ELEMENT imgName (#PCDATA)>

<!--Defines child elements of extras with PCDATA input-->
<!ELEMENT cartridgeName (#PCDATA)>
<!ELEMENT cartridgeSize (#PCDATA)>

<!--Defines child elements review with PCDATA input-->
<!ELEMENT userName (#PCDATA)>
<!ELEMENT reviewText (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

<!--Defines the attributes of the elements-->
<!ATTLIST title modeOfDelivery (meatSpace|cyberSpace) "meatSpace">
<!ATTLIST winePairing wineType (Red|White|LSD) "Red">

<!--Defines the entitys-->
<!ENTITY nj "NuraJakâ„¢">
<!ENTITY warn "Warning, use of this product may cause:">


]>
<!--XML Tree Structure-->
<products>
	<rental>
		<title></title>
		<url></url>
		<image>
			<imgUrl></imgUrl>
			<imgName></imgName>
		</image>
		<description></description>
		<winePairing></winePairing>
		<category></category>
		<cost></cost>
		<tags></tags>
		<parentalRating></parentalRating>
		<condition></condition>
		<healthWarning></healthWarning>
		<powerUse></powerUse>

		<extras>
			<cartridgeName></cartridgeName>
			<cartridgeSize></cartridgeSize>
		</extras>
		
		<review>
			<userName></userName>
			<reviewText></reviewText>
			<rating></rating>
		</review>

	</rental>
</products>
